{% set name = "sphinx-github-changelog" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ffbb65206c8be8e84f39b4de7a44e98e92312fe38b363e7f016277443d493700

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - uv-dynamic-versioning
  run:
    - python >={{ python_min }}
    - docutils
    - httpx
    - myst-parser >=5.1.0
    - sphinx

test:
  imports:
    - sphinx_github_changelog
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/ewjoachim/sphinx-github-changelog/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Build a sphinx changelog from GitHub Releases
  description: |
    sphinx-github-changelog is a sphinx plugin that provides a directive which,
    when built, will display a changelog generated from the github releases
    of the project
  doc_url: https://sphinx-github-changelog.readthedocs.io/en/latest/
  dev_url: https://github.com/ewjoachim/sphinx-github-changelog/

extra:
  recipe-maintainers:
    - ewjoachim
    - curtisma
