{% set name = "sphinx-github-changelog" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 20affb353bf02c89b868c2e5b9c61693dd22f3d2b2e134063c49f9e0d69352a5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.7
    - pip
    - poetry-core
  run:
    - python >=3.7
    - docutils
    - importlib-metadata
    - requests
    - sphinx

test:
  imports:
    - sphinx_github_changelog
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ewjoachim/sphinx-github-changelog/
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Build a sphinx changelog from GitHub Releases
  description: |
    sphinx-github-changelog is a sphinx plugin that provides a directive which,
    when built, will display a changelog generated from the github releases
    of the project
  doc_url: https://sphinx-github-changelog.readthedocs.io/en/latest/
  dev_url: https://github.com/ewjoachim/sphinx-github-changelog/

extra:
  recipe-maintainers:
    - ewjoachim
    - curtisma
