{% set name = "sphinx-github-changelog" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6437fd910ff863e8809bfe709979bfbf87244d9e8d774aa95040250cb7030428

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - docutils
    - importlib-metadata
    - requests
    - sphinx

test:
  imports:
    - sphinx_github_changelog
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/ewjoachim/sphinx-github-changelog/
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Build a sphinx changelog from GitHub Releases
  description: |
    sphinx-github-changelog is a sphinx plugin that provides a directive which,
    when built, will display a changelog generated from the github releases
    of the project
  doc_url: https://sphinx-github-changelog.readthedocs.io/en/latest/
  dev_url: https://github.com/ewjoachim/sphinx-github-changelog/

extra:
  recipe-maintainers:
    - ewjoachim
    - curtisma
